"""A SQLGlot dialect that faithfully round-trips RisingWave's streaming SQL.

The tile engine's SQL is generated by the ``build_*_select`` f-string builders (``sql_builders.py``), isolated
behind each ``TilePlan`` node's ``.select()``. Migrating that codegen to a composable SQLGlot AST (so the
relational core is built structurally rather than by string concatenation) needs a dialect that can PARSE and
GENERATE the RisingWave streaming constructs without mangling them. SQLGlot ships a ``risingwave`` dialect, but
(as of 30.11) it only adds ``SINK`` / ``SOURCE`` DDL keywords and inherits Postgres for the rest, so it does
not round-trip the streaming-SELECT constructs the tile engine relies on:

  - ``now()`` — RisingWave's dynamic temporal-filter trigger (it re-evaluates as the watermark advances,
    driving a now()-anchored rollup) — is folded to ``CURRENT_TIMESTAMP``. That is a SEMANTIC change:
    ``CURRENT_TIMESTAMP`` is fixed per transaction, so the dynamic filter would stop advancing.
  - ``INTERVAL '<n>' <unit>`` (RisingWave's form) drifts to Postgres' ``INTERVAL '<n> <unit>'``.
  - ``EMIT ON WINDOW CLOSE`` — a streaming materialized view's emit policy — FAILS TO PARSE outright.

This dialect adds the parser + generator support for those, so RisingWave streaming SQL survives a
``parse -> AST -> generate`` round-trip semantically intact (now() preserved, the RisingWave interval form,
EMIT ON WINDOW CLOSE retained). It subclasses the RELEASED ``risingwave`` dialect — it is a vendored
enrichment, not a fork; in an upstream SQLGlot contribution these additions fold into ``RisingWave`` itself.

NOT byte-identical to the f-string builders, and not meant to be: SQLGlot models known aggregates (sum / count
/ min / max) and ``date_trunc`` as typed nodes that render with a canonical (upper) spelling, so a codegen
swap re-baselines the SQL goldens to that canonical form — a one-time, semantically-equal change. The
round-trip guarantee here is SEMANTIC + idempotent (re-rendering the output is stable), which is the gate the
codegen swap rides on. Round-trip with ``normalize_functions=False`` to keep anonymous function spellings.
"""

from __future__ import annotations

from sqlglot import exp
from sqlglot.dialects.risingwave import RisingWave

# A streaming materialized view's emit policy, modeled as a marker on the query so it round-trips. RisingWave
# places it after the query body (after GROUP BY / ORDER BY), so the generator appends it last.
_EMIT_ON_WINDOW_CLOSE = "ON WINDOW CLOSE"


class RisingWaveStreaming(RisingWave):
    """RisingWave dialect + faithful round-trip of the streaming-SELECT constructs the stock dialect drops."""

    class Parser(RisingWave.Parser):
        def _parse_query_modifiers(self, this):
            this = super()._parse_query_modifiers(this)
            # ``EMIT ON WINDOW CLOSE`` is a trailing clause after the query body and is not a SQLGlot token, so
            # consume it by text. (RisingWave also accepts ``EMIT ON WINDOW CLOSE WITH (...)``; the bare form
            # is what a tile materialized view emits.) ``EMIT`` halts the base modifier loop first, so the
            # ``WINDOW`` here is never mistaken for a named-window modifier.
            if this is not None and self._match_text_seq("EMIT", "ON", "WINDOW", "CLOSE"):
                this.set("emit", exp.var(_EMIT_ON_WINDOW_CLOSE))
            return this

    class Generator(RisingWave.Generator):
        TRANSFORMS = {
            **RisingWave.Generator.TRANSFORMS,
            # Preserve RisingWave's dynamic now() trigger; do NOT fold it to the per-transaction-fixed
            # CURRENT_TIMESTAMP (the Postgres base does), which would freeze a now()-anchored rollup.
            exp.CurrentTimestamp: lambda self, e: "now()",
        }

        def interval_sql(self, expression: exp.Interval) -> str:
            # RisingWave form: ``INTERVAL '<n>' <UNIT>`` — the value quoted, the unit a trailing bare keyword.
            # (The Postgres base emits ``INTERVAL '<n> <unit>'``, folding the unit into the quoted literal.)
            this = expression.this
            value = this.name if this else ""
            unit = expression.args.get("unit")
            unit_sql = unit.name if unit else ""
            return f"INTERVAL '{value}' {unit_sql}".rstrip()

        def after_limit_modifiers(self, expression: exp.Expr) -> list[str]:
            modifiers = super().after_limit_modifiers(expression)
            if isinstance(expression, exp.Select) and expression.args.get("emit"):
                modifiers.append(" EMIT ON WINDOW CLOSE")
            return modifiers
